### PR TITLE
[Sources] Allow bzip and binary MIME types for Packages.bz2 verification

### PR DESCRIPTION
**Pull request by absidue**

### CODE REVIEW

**Comment by wstyres** [comment]
Whats the reason for octect-stream here?

**Comment by absidue** [comment]
Most of the sources in the screenshots provided by Rayray on [discord](https://discordapp.com/channels/566255609251364864/572784833714192395/699989001754378270) returned Packages.bz2 with the MIME type `application/octet-stream` in my testing

**Comment by wstyres** [comment]
Wouldn't this be useful for the other file types (`.xz`, `.gz`, etc.) as well? I'm also concerned about these being false positives which would bring us back to the original problem of verifying the clipboard.

**Comment by absidue** [comment]
Probably, I don't like it either. What would also help would be an addional check for `/Release`. Another thing that would help at least on the performance side would be to combine the black list and `HEAD` requests, so youtu.be and similar URLs would be filtered out straight away.

**Comment by wstyres** [comment]
Repositories aren't actually required to have a Release file so that's why we don't check for it. I think combining this with the blacklist might be a good idea though.

**Comment by absidue** [comment]
I'll work on it

**Comment by absidue** [comment]
@wstyres This is complete, unless you want to add some more domains to the blacklist first?

**Pull request merged**
