### PR TITLE
[Packages, Repo, Search] URL detection for package long description and Table View Indexes.

### PR DESCRIPTION
**Pull request by PoomSmart**
This will also serve #105

### CODE REVIEW

**Comment by aabosh** [comment]
Great work! Just tested it. I feel that the table view indexes are unnecessary for the Search tab as the search term should cover it. Similarly, with the Repos tab—is it needed? I personally have ~15 repos and don't see the index being helpful. What do you think? Also, I feel we should remove all the characters in the list that don't have at least one result so that the full alphabet doesn't show. The Packages tab is great, works super well. If you get the chance, could you add headers for each letter? (you can reuse `tableView viewForHeaderInSection`)

**Comment by PoomSmart** [comment]
1. For Search: I can agree with that
2. For Repos: It’s possible for someone to have many more repos added, at least we can give them some assistance and it won’t hurt having it, besides.
3. Having only alphabets matching prefixes of the actual data is a good idea.
4. For having a header for each alphabet: that was my mistake. I thought the list without headers is common. I will follow the mainstream then.

**Comment by wstyres** [comment]
Possibly only showing the slider it the contents are greater than a certain number? Ex: don’t show if 10 repos/packages but 35 should show

**Comment by aabosh** [comment]
Nice! Making progress. There seems to be a bug where header views will take up a lot of space? I can always reproduce it with just the xTM3x repo installed (default settings).
image

Similarly, this also seems to occur in the packages view controller. 
image

**Comment by PoomSmart** [comment]
@aabosh The issues you mentioned earlier seem to be all solved.

**Comment by aabosh** [comment]
Works great! Amazing work.

**Pull request merged**
