### PR TITLE
Improved german translation

### PR DESCRIPTION
**Pull request by ann0see**
There are some minor issues with the german translation. This PR fixes some.

### CODE REVIEW

**Comment by WDKFernando** [comment]
Good cleanup of the translation. 
I think tho the switch from “inkompatibel “ to “nicht kompatibel” is a bit redundant. Anyways, what do you think about using the imperative for the social media related strings? Would it be better, or nah?

**Comment by ann0see** [comment]
In my opinion one can „nicht ... kompatibel“ easier (and faster) since „nicht“ comes much earlier in the sentence. 
Using an imperative – in my opinion – is better since it’s stronger.

**Comment by ann0see** [comment]
... one can understand ...
Also „Vorgestellt“ for featured in my opinion is different. 
„Vorgeschlagen“ or „Highlights“ would be better. I think it should be discussed with other German translators. 
Also „Es könnte Probleme verursachen, wenn du es zu Zebra hinzufügst, was eine mögliche Wiederherstellung von Zebra verursachen könnte.“ 
is kind of difficult to understand and maybe not correctly translated. Maybe we can find a better translation.

**Comment by wstyres** [comment]
I'll merge this but in the future, check out https://translate.getzbra.com/. All of the translations are hosted there.

**Comment by ann0see** [comment]
The new versions basically undid the changes. Will look on the website you mentioned.

**Comment by wstyres** [comment]
Sorry about that, there must have been a glitch when porting it over to the site. If you make the changes on the site though there shouldn't be any issues.

**Comment by ann0see** [comment]
That’s no problem at all. Almost all changes are already proposed there. Could you accept them there (the worst one is Gesundheit und Fitneß it should be Gesundheit und Fitness).

**Pull request merged**
