### PR TITLE
Implement new sbreload command for a faster respring

### PR DESCRIPTION
**Pull request by JAKESNAKE523**
The Chimera jailbreak brought a new way to respring called sbreload.  I took advantage of that and Implemented it into Zebra. Don't worry, I also made it compatible with the old respring if the sbreload binary isn't found on the device.

### CODE REVIEW

**Comment by sckova** [comment]
worldstar

**Comment by wstyres** [comment]
Awesome! I had no idea that this was fixed with the chimera jailbreak. However, there is a problem with your implementation, this checks if the file exists at `/usr/bin/sbreload` but that file exists on every device with UIKit Tools installed (whether chimera, electra, or other jailbreaks) but Chimera is the only jailbreak that I know of that it works on (uncover's does not) so we'll have to find another way of detecting this because if you're on uncover this will not respring the device.

**Comment by JAKESNAKE523** [comment]
I will work on a new implementation then. I have a couple ideas.

**Comment by wstyres** [comment]
Looks good to me! Might cause problems in the future in case uncover decides to update sbreload but I might be able to find another way to detect it eventually.

**Pull request merged**
