### PR TITLE
[Settings] Add tap cell to toggle to all switches

### PR DESCRIPTION
**Pull request by absidue**

### CODE REVIEW

**Comment by wstyres** [comment]
Do you think there could be a better implementation of this? Writing the same code for every cell (which I know we already do) is a little bit annoying so if you're already rewriting it I wonder if there is a better implementation that could be used.

**Comment by absidue** [comment]
We can definitely create custom table cells.

The most common table cells are switches, buttons (the whole reset section), what I am calling link cells that take you deeper into the settings pages (1. section on the first page of the settings) and radio selectors (accent color, swipe actions display, language)

The styling and basic functionality (setting, toggling and fetching a switch's state) could definitely be moved to custom cells.

We can also try and implement the functionality of link and radio cells in a custom table view controller and extend all pages from that.

**Comment by absidue** [comment]
I'll leave this pull request open until I create a separate one with custom table cells as roughly outlined above

**Comment by absidue** [comment]
Closing in favour of #1445

**Pull request closed without merging**
