### PR TITLE
Start Repo URL Blacklist On Clipboard Manager

### PR DESCRIPTION
**Pull request by M4cs**
Fixing PR because old was from a fork that was outdated. Sorry for the dupe!

This basically starts a blacklist of common social media, media links that people may have saved!

### CODE REVIEW

**Comment by va2ron1** [comment]
Hi! I don't think this is a good idea, but if this gets implemented, the list need to be read it from a file or something, not hard coded or you will be restricting users freedom. Also the file can be updated without updating the app.

**Comment by TheRealKeto** [comment]
Essensially, this is to stop users from adding links that are not repos. An example of this would be if an unexpirienced user attempts to add a YouTube link (thinking its a repository) to Zebra, which, in the end, doesn't "restrict the user".

**Comment by wstyres** [comment]
I think it is a good idea because the clipboard repo popup can sometimes get annoying if you have a youtube or twitter link. I'll take a look and then possibly merge.

**Comment by M4cs** [comment]
@va2ron1 this isnt restricting anybody from adding an actual repo. This simply blocks common social media app links, if you look at the commit youll see there are no repo URLs. If you have a twitter link, reddit link, or youtube link in your clipboard it can be annoying when it asks to add this instead of just adding a repo. 

Thanks @wstyres for the merge 👍

**Comment by va2ron1** [comment]
Yes, I know and that was my suggestion to read the urls from a file. This feature could mean or not, wrong things in the future. But I made a mistake commenting on this, I thought that I saw the code in the add repo method and not in the clipboard method.

Great work 👍🏻

**Pull request merged**
