### PR TITLE
Update settings page to better support localizations

### PR DESCRIPTION
**Pull request by relisiuol**
#511

### CODE REVIEW

**Comment by worldlydev** [comment]
Ooh. That was fast. Can you send me a compiled  .Deb with all your changes? I can't compile it as I don't have a Mac and really want to see if it fixes the settings page for me.

**Comment by relisiuol** [comment]
https://www.mediafire.com/file/s5kvpva8yp8ovv6/xyz.willy.zebra_1.0%7Ebeta24-1_iphoneos-arm.deb/file

**Comment by worldlydev** [comment]
> https://www.mediafire.com/file/s5kvpva8yp8ovv6/xyz.willy.zebra_1.0%7Ebeta24-1_iphoneos-arm.deb/file

Thanks it looks great 😎Any chance you can do the same for for the other UISegmentedControls? For "featured type" and for "swipe actions show as"?

**Comment by relisiuol** [comment]
Cancelled.

**Comment by relisiuol** [comment]
Better implementation.

**Pull request merged**
