### PR TITLE
Localization Support

### PR DESCRIPTION
**Pull request by rweichler**
This is not ready for review. Well, I guess it kinda is. Feel free if you want.

TODO
- [x] `ZBQueue` needs to be refactored to not rely on raw strings for "Unresolved Dependencies", "Conflictions", "Install", "Remove", "Upgrade", etc.
    * In order to achieve this, I think`queueToKey:` and `keyToQueue:` need to be class methods. And "Unresolved Dependencies" and "Conflictions" need to be added to the `ZBQueueType` enum.
- [x] Probably use a standard way of generating Localizable.strings instead of my shitty Lua script. [BartyCrouch](https://github.com/Flinesoft/BartyCrouch) maybe? Or perhaps just get rid of it entirely, as adding new strings one-by-one will be kinda ez after I'm done with this.
- [x] Figure out how to make localizing .xibs/.storyboards not shitty. Seems like it needs to be in a different `.strings` file, with a cryptic ID in order for it to work right. Based on my extremely limited research on this, I think setting the titles of the buttons and everything should be done programmatically in `viewDidLoad:` or something, that way we can bypass this
- [x] Manual testing.
- [x] Generally, figure out a workflow for translators that is painless as possible.

Anyway, workflow for this is, find strings in the Xcode project, add them to `strings_easy_to_edit.txt`. Then cd into the repo and run `lua generate_localizable.lua > Zebra/Base.lproj/Localizable.strings`. Then you should be good to go.

Idk how you guys like to do it but I usually spam a bunch of commits in the PR, then once approved I do squash+merge.

### CODE REVIEW

**Comment by wstyres** [comment]
Queue localization can now be easily accessed by `-displayableNameForQueueType:` as of #394.

**Comment by rweichler** [comment]
Okay. I think I'm done.

Decisions I've made:
* Not using BartyCrouch because eww dependencies. We will edit it manually like cavemen.
* Setting everything in `Localizable.strings`, Used a new method `applyLocalization` which is called from `viewDidLoad` which basically sets `label.text = NSLocalizedString(label.text, @"")`. That way the text set in IB isn't useless.
* Basically the workflow is just edit Localizable.strings.

ALSO: I intentionally did not touch `ZBPackageDepicionViewController`, it needs to be refactored a bit in order to support Localization. I didn't do it in this PR because I just wanna get this in, merging master all the time is kinda painful.

**NEXT STEPS**:
* Refactor `ZBPackageDepictionViewController`. It's too hard to add localization to it now. That, I think, is the only place where it's not supported.
* Have someone try to translate a language like French or Spanish.
* Add docs.

**Comment by relisiuol** [comment]
> **NEXT STEPS**:
> 
>     2. Have someone try to translate a language like French or Spanish.

I can do that, I'm yourepo admin & I'm French. Just tell me what I should do please.

**Comment by rweichler** [comment]
My method of using the english translation as a key proved ineffective. Context matters in certain languages. Example: Remove could mean "Remove tweak" or "Remove from wish list", which could have slightly different translations depending on the language.

So, it's gotta be the conventional way that Apple wants us to do. Oh well

**Pull request merged**
