### PR TITLE
Add Provides: cydia to the control file

### PR DESCRIPTION
**Pull request by mwoolweaver**
Will help negate the Essential from apt.bingner.com package always requiring an update when Cydia is not installed.

This will not affect Cydia in any way. But will only create a virtual package of Cydia in Cydia's absence. 

[Virtual packages - Provides](https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides)

### CODE REVIEW

**Comment by PoomSmart** [comment]
A whitespace after the colon please.

**Comment by mwoolweaver** [comment]
Done! Sorry I forgot to put the first time.

**Comment by wstyres** [comment]
Seems alright to me, have you done any testing with it?

**Comment by mwoolweaver** [comment]
Works as intended here.

**Comment by mwoolweaver** [comment]
> [If you install this package and then try to uninstall Cydia you will notice that Zebra tries to uninstall the Essential package and Cydia Translations. And if you allow Zebra to uninstall these 2 packages (it should not uninstall either per the control file I linked to). Now try to install either the Essential package or Cydia Translations, they will succeed w/o Zebra queuing up Cydia as it should](https://github.com/wstyres/Zebra/issues/1083#issue-599344088)]

Might get 1-2 extra issues about this until it's sorted out.

**Pull request closed without merging**
