### PR TITLE
Change console monospaced font

### PR DESCRIPTION
**Pull request by NSExceptional**
Courier is probably the worst monospace font out there. We should use the system monospaced font if available; otherwise, use Menlo, which is easier to read than Courier. This also removes the executable bits from the control file and Makefile, which shouldn't be there.

I can change the base branch, remove the first commit, etc; anything you need to get this merged, just lemme know!

### CODE REVIEW

**Comment by wstyres** [comment]
Could you change the branch from `master` to `1.1`? We're currently in the beta testing phases of 1.1 and not releasing any 1.0.x builds anymore unless we have to.

Also, looks like you added the new font to ZBRefreshViewController (which handles the console for the database) but not the console for the package installation / removal which is in ZBConsoleViewController. Could you add it there too? Sorry about the confusion for this one, I've been meaning to merge the two controllers and clean them up for awhile.

Thanks for pointing out the executable bits as well, not sure why they were there to begin with.

**Comment by NSExceptional** [comment]
Question about the `UIColor (Private)` extension: are those methods confirmed to exist prior to iOS 13 all the way back to iOS 9?

**Comment by NSExceptional** [comment]
Good to go

**Comment by PoomSmart** [comment]
`UIColor (Private)` stuff is there since iOS 7

**Pull request merged**
