### PR TITLE
Added more localization and fixed typo

### PR DESCRIPTION
**Pull request by eve0415**
More translations to do!

Removed duplicate string.

I arranged it to make it cleaner.
Maybe we might have to re-translate some strings. (I hope not)

By the way what's "Modiy"

### CODE REVIEW

**Comment by worldlydev** [comment]
"\"Random\" will display random packages from all repositories that you have added to Zebra." = "\"Random\" will display random packages from all repositories that you have added to Zebra.";
"\"Repo Featured\" will display random packages from repos that support the Featured Package API." = "\"Repo Featured\" will display random packages from repos that support the Featured Package API.";

Should have _repo_, _repos_, and _repositories_ changed to sources in my opinion. Like it was before you moved the strings around.

**Comment by worldlydev** [comment]
While your at it maybe at localization support to these:
6E6E2136-58E9-47A3-A3F9-51FF9AF27A3C
C26CC635-F8B7-4C8F-A294-AF862CF58C1E

**Comment by worldlydev** [comment]
Also not sure how Wilson feels about this so maybe some feeback first. In my opinion it would be cool if the little easter eggs from the console were localized as well.

The strings that appear when removing Zebra, reinstalling Zebra, etc.
Such as : _Goodbye forever :(_

**Comment by eve0415** [comment]
> ""Random" will display random packages from all repositories that you have added to Zebra." = ""Random" will display random packages from all repositories that you have added to Zebra.";
> ""Repo Featured" will display random packages from repos that support the Featured Package API." = ""Repo Featured" will display random packages from repos that support the Featured Package API.";
> 
> Should change _repo_, _repos_, and _repositories_ to source or sources. Like it was before you moved the strings around.
> 
> Same goes for these as well (and whatever else I may have missed):
> 
> "Repo Featured" = "Repo Featured";
> "Random" = "Random";
> "Select Repos to be Featured" = "Select Repos to be Featured";
> "Featured Repos" = "Featured Repos";

I thought about changing those to "source" as well as I remember @wstyres was talking about unifying.  I need to ask Wilson for that if I should change it or leave it as it is as those strings were coded like this.
https://github.com/wstyres/Zebra/blob/fedf1499474183607eeb21223964e77e3b09c045/Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m#L241
Check the debug version.

> Also not sure how Wilson feels about this so maybe some feeback first. In my opinion it would be cool if the little easter eggs from the console were localized as well.
> 
> The strings that appear when removing Zebra, reinstalling Zebra, etc.
> Such as : _Goodbye forever :(_

Need to hear from Wilson.

> While your at it maybe add localization support to these?
> 6E6E2136-58E9-47A3-A3F9-51FF9AF27A3C
> C26CC635-F8B7-4C8F-A294-AF862CF58C1E

And for this I totally forgot about it. Thanks for reminding me!!

Plus I have to remove all those SDWebImage things. Don't know how though

**Comment by worldlydev** [comment]
> 
> And for this I totally forgot about it. Thanks for reminding me!!
> 
> Plus I have to remove all those SDWebImage things. Don't know how though

Check the Crowdin. 
15B52C8A-A56A-4DB3-8E1A-BA3F7888B5AB
There's only 5 strings that contain _repo_. You changed them back to repo from source.

**Comment by eve0415** [comment]
>
https://github.com/wstyres/Zebra/blob/fedf1499474183607eeb21223964e77e3b09c045/Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m#L232
>
https://github.com/wstyres/Zebra/blob/fedf1499474183607eeb21223964e77e3b09c045/Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m#L241
>

C64BF06E-BDCE-4C2E-93B5-2B3EC926D9FD

I changed it because the base code was like this. I need to check with Wilson about this if I should change it to source or not

**Comment by eve0415** [comment]
https://github.com/wstyres/Zebra/blob/fedf1499474183607eeb21223964e77e3b09c045/Zebra/Database/ZBDatabaseManager.m#L325
↓
[self bulkPostStatusUpdate:[NSString stringWithFormat:@"%@\n", NSLocalizedString(@"No packages file for %@", @""), source.repositoryURI] atLevel:ZBLogLevelError];

Am I writing right or wrong? Please correct it if it's wrong. I never wrote Obj-C

**Pull request merged**
